CREATE  TABLE Products (
       id BIGINT GENERATED BY DEFAULT AS IDENTITY,
       name VARCHAR(100) NOT NULL,
       description VARCHAR(500) NOT NULL,
       price NUMERIC NOT NULL,
       PRIMARY KEY (id)
);
